name: Exec Command

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment where to execute the command'
        required: true
        type: choice
        default: test
        options:
          - test
      command:
        description: 'Command to execute in the docker container'
        required: true
        type: string

jobs:
  exec:
    name: Exec Command
    runs-on: test01
    steps:
      - name: Setup env
        id: env
        run: |
          echo "repository_name=${GITHUB_REPOSITORY##*/}" >> $GITHUB_OUTPUT

      - name: Exec Command
        env:
          DOCKER_COMPOSE_FILE: /opt/docker-compose/docker-compose-${{ steps.env.outputs.repository_name }}.yml
          DOCKER_SERVICE_NAME: ${{ steps.env.outputs.repository_name }}-${{ github.event.inputs.environment }}-php
        run: |
          sudo chroot /host/rootdir docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} -p ${{ steps.env.outputs.repository_name }} exec ${{ env.DOCKER_SERVICE_NAME }} ${{ github.event.inputs.command }}
